name: Test Automation WorkFlow

on:
  schedule:
   - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation with Maven
      run: mvn test -X -Dbrowser=Chrome -DisLamdaTest=true -DisHeadless=false
      
    - name: Upload a logs Artifact
      if: always()
      uses: actions/download-artifact@v6.0.0
      with:
       name: Test logs
       path: logs

    - name: Upload Test Reports
      if: always()
      uses: actions/download-artifact@v6.0.0
      with:
       name: Test Reports
       path: report.html

    - name: Test Execution Status
      run: echo "Test execution completed"

   
